### ISSUE TITLE
Start-up crash (Forge-14.23.0.2493. nuclearphysics-1.12.2-0.1.23

### ISSUE THREAD

**Issue by Beanius** [halvors/Quantum#11]
https://gist.github.com/Beanius/f450716089de60a86883c468f197b399

**Comment by halvors** [comment]
@Beanius This is now fixed, i'm currently at work, will have a new build out later today. In the meanwhile you could use build 21. It shoulf work fine but without the othet fixes of build 23.

Thank you for helping me out by reporting this :-)

**Comment by Beanius** [comment]
Yah 21 works. Cheers for fast response and upcoming fix! B)

**Comment by halvors** [comment]
Just uploaded the new build (24) fixing this issue to CurseForge.
