### ISSUE TITLE
How to start the fusion reactor？

### ISSUE THREAD

**Issue by forestbat** [halvors/Quantum#13]
@halvors 
![2017-10-06_22 57 53](https://user-images.githubusercontent.com/23413915/31284229-8759f0be-aaea-11e7-9a40-1f033434b822.png)
![2017-10-06_23 05 36](https://user-images.githubusercontent.com/23413915/31284379-ee5d969e-aaea-11e7-8d19-f935b3f8830c.png)
![2017-10-06_22 58 11](https://user-images.githubusercontent.com/23413915/31284230-8768ba86-aaea-11e7-8091-b81948a6ae2c.png)
Are there any mistakes of the structure？How to start the fusion reactor to get energy？

**Comment by halvors** [comment]
Think you're structure doesn't allow plasma to spawn, it's the plasma itself that boils the water into steam.

![2017-10-09_00 33 00](https://user-images.githubusercontent.com/620303/31321694-eddacbd8-ac89-11e7-886e-d328560d6878.png)

**Comment by Eclairictus** [comment]
*sry for my bad english

I cant start the fusion reactor too.

     Plasma is not generated by plasma heater.
     And don't load mekanism's liquid deuterium.
     Reactor cell don't load deutrium (and cell).

I want you to tell me how to do or reference video :)

![2017-10-25_23 43 56](https://user-images.githubusercontent.com/13760011/32005283-d474d730-b9de-11e7-9c43-e14bd2575451.png)
![2017-10-25_23 33 01](https://user-images.githubusercontent.com/13760011/32005285-d4c7e10a-b9de-11e7-9208-ca5302b3a297.png)
![2017-10-25_23 57 50](https://user-images.githubusercontent.com/13760011/32005873-58df90ea-b9e0-11e7-9f8e-af838e3cf608.png)

Forge version 14.23.0.2515
nuclearphysics-1.12.2-0.1.24.jar

**Comment by halvors** [comment]
@Eclairictus You need to provide the plasma heater with both deuterium and tritium as well as energy.

**Comment by Eclairictus** [comment]
@halvors  I didnt know need deuterium and tritium for working...ty!!
I think  succeeded to generate plasma, but temperature is not raised.



cause of wrong structure?

![2017-10-30_22 18 51](https://user-images.githubusercontent.com/13760011/32172837-5f8a4460-bdc0-11e7-95e8-adb3d24367d3.png)
![2017-10-30_22 18 57](https://user-images.githubusercontent.com/13760011/32172838-600dc754-bdc0-11e7-9d44-f417559a9e1a.png)

And texture (deuterium and tritium, plasma) is buggily.
![2017-10-30_22 26 25](https://user-images.githubusercontent.com/13760011/32173162-64c8ed5e-bdc1-11e7-9d6f-31a075b4625b.png)

**Comment by halvors** [comment]
I know it's somewhat buggy, still testing this.
But the temperature in the reactor should not actually be shown, as long as the plasma is spawning around you're ok. Not the reactorblock itseld that is heated.

**Comment by halvors** [comment]
And for the deuterium and tritium, you're using the fluids from mekanism right? I cannot fix them impropetly registering the textures, guess textures in world i rendering fine? 

If problem persists i will look into fixing this in mekanism and sending in a patch to the developers.

**Comment by Eclairictus** [comment]
Im using Nuclear-Physics's deuterium and tritium.

I tested environment only mekanism and this mod, texture bug is not caused.
And, plasma is generated!
I dont know why this result...

So maybe  other mod do something wrong.
Need for paste installing mod ?

**Comment by halvors** [comment]
Yeah. That would be helpful. :-)

**Comment by Eclairictus** [comment]
I hope this is your help!
Minecraft version 1.12
Forge version 14.23.0.2515

> CutAllSMP_v2.5.2.zip
DigAllSMP_v2.3.2.zip
MineAllSMP_v2.6.5.zip
RosettaEnchantTable_v0.0.8.zip
AdvancedRocketry-1.12.2-1.2.3.jar
AutoRegLib-1.3-14.jar
BedrockLayer_1.11.2-v1.2.4.jar
BrandonsCore-1.12-2.3.3.132-universal.jar
calculator-1.12.2-5.0.1.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12-0.0.14.18.jar
CodeChickenLib-1.12-3.1.3.313-universal.jar
CoFHCore-1.12-4.3.6.14-universal.jar
CoFHWorld-1.12-1.0.1.8-universal.jar
CTM-MC1.12-0.2.3.9.jar
Draconic-Evolution-1.12-2.3.4.265-universal.jar
EnderRift-1.12.1-2.1.9.jar
extrautils2-1.12-1.6.4.jar
ExtremeReactors-1.12-0.4.5.44.jar
FastLeafDecay-v14.jar
gigaherz.commons-1.12.1-0.6.4.jar
GraphLib-1.3.0.jar
gravestone-1.10.0.jar
Hwyla-1.8.20-B35_1.12.jar
ImmersiveEngineering-0.12-74-core.jar
ImmersiveEngineering-0.12-74.jar
immersivepetroleum-1.12-1.1.3.jar
immersivetech-1.12-1.3.4.jar
industrialcraft-2-2.8.16-ex112.jar
InventoryTweaks-1.63.jar
IvToolkit-1.3.3-1.12.jar
jei_1.12.2-4.8.0.105.jar
journeymap-1.12.2-5.5.1.jar
LibVulpes-1.12.2-0.2.6-universal.jar
mcjtylib-1.12-2.4.4.jar
**Mekanism-1.12.1-9.4.1.326.jar**
MekanismGenerators-1.12.1-9.4.1.326.jar
MekanismTools-1.12.1-9.4.1.326.jar
Neat 1.4-15.jar
NotEnoughItems-1.12-2.4.0.231-universal.jar
NuclearCraft-2.5a--1.12.2.jar
**nuclearphysics-1.12.2-0.1.24.jar**
OptiFine_1.12.2_HD_U_C6.jar
OreExcavation-1.4.109.jar
Quark-r1.3-112.jar
RebornCore-1.12.2-3.4.8.138-universal.jar
RebornStorage-1.12-2.0.1.6.jar
RecurrentComplex-1.4.5.1.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
refinedstorage-1.5.21.jar
refinedstorageaddons-0.2.jar
rftools-1.12-7.12.jar
rftoolsdim-1.12-5.05.jar
sonarcore-1.12.2-5.0.2.jar
StorageDrawers-1.12.1-5.3.3.jar
TakeOutSpawner-1.12-0.4.0.jar
theoneprobe-1.12-1.4.18.jar
ThermalExpansion-1.12-5.3.6.20-universal.jar
ThermalFoundation-1.12-2.3.6.16-universal.jar
twilightforest-1.12.2-3.2.155-universal.jar
UniDict-1.12.1-1.0.jar
WailaHarvestability-mc1.12-1.1.12.jar
WanionLib-1.12.1-1.0.jar
xnet-1.12-1.4.1.jar
zerocore-1.12-0.1.1.0.jar
>

**Comment by halvors** [comment]
But you have mekanism installed. And its loaded before nuclear physics. So then you are using mekanism deuterium and tritium. And the problem with the textures must lie there.

When mekanism registers deuterium and tritium first. A fluid with tjat name already exists, and we are using that for compatibility between mods :-)

**Comment by jayburn00** [comment]
I seem to be running a much older version 1.6.4.  I can't find instructions for how to get plasma from heater to reactor cell, and I can't turn on heater either.  I think this is actually an issue of unable to find documentation, not bugs, but I can't find where to ask.  You say refer to the atomic science wiki, but atomic science nuclear fusion works much differently and is much more simple and unrealistic (works differently from yours).

**Comment by halvors** [comment]
@jayburn00 I see. Sorry for late answer. The reason this differs from the classic Atomic-Science is because my mod is based on the latest work by Calclavia. The fusion reactor from Electrodynamics.

To get the plasma from the Plasma Heater (assuming that there is plasma generated, need to be atleast 1000L i think) use some sort of fluid pipes to transport it.
Like the the Mechanical Pipe in Mekanism.

**Comment by halvors** [comment]
@jayburn00 Also, if the general opinion is that the original Atomic Science way was better, there is possible to rewrite the mechanics to work like that.

**Comment by Njet75** [comment]
Thanks for the great work.
I really missed this mod since 1.6.4.
First bug i noticed is that you cant have  NuclearCraft made by tomdodd4598 installed.
You get wrong plasma.
Second bug is after a while running the water stops boiling and generator stop working.
Plasma still spawns.(edit happens when i Place gasfunnels).
Must restart whole game to make it work again
I use creative tank from Mekanism.
/Michael

**Comment by Njet75** [comment]
I´m all for a rewrite to original Atomic Science.
Calclavia never got the new system to work without bugs.
/Michael

**Comment by halvors** [comment]
@Njet75 Thanks for reporting this! What do you mean by that you get the wrong plasma? Plasma from NuclearCraft and NuclearPhysics should be interchangeable if they've registered it right with Forge. But maybe it wont't "eat the world" around and set things on fire when released into the world.

**Comment by Njet75** [comment]
Maybe its a Forge issue.I will make a Clean install and test diffrent Forge version.
Witchversion was it buildt with?
/ Best Michael

**Comment by Njet75** [comment]
Tested with lastest build and this happens.
Forge 2618
Hope this helps.
![2018-04-02_12 59 27](https://user-images.githubusercontent.com/8996171/38194550-7ac6f8e6-3678-11e8-8a2a-87832425b29e.png)
![2018-04-02_13 10 33](https://user-images.githubusercontent.com/8996171/38194562-8a1178d0-3678-11e8-804a-4793ad9918b2.png)

**Comment by halvors** [comment]
@Njet75 
It was built with latest recommended version of Forge. If you're on 1.12.2 as most is at the moment that would be build 2611.

I'm releasing a fix for the bug where generators was stopping to work.
In my test's it solved the issue, could you please verify as well? :)

Also when reporting, please do make a new issue as it's easier to make sure it properly tracked :)

**Comment by Njet75** [comment]
@halvors 
Latest version and Forge 2611 did the trick.
Yes I will make new issue in the future if I find any bugs :).
Thanks for all the work you put into this mod.
/Best Michael

**Comment by halvors** [comment]
@Njet75 Glad to hear that fixed the issue :) And thanks again for reporting :)

**Comment by halvors** [comment]
Since this is way old now with recent issues now discussed in own reports, i'll close this.
