### ISSUE TITLE
Particle accelerator results game crash

### ISSUE THREAD

**Issue by ZHENGLOC** [halvors/Quantum#14]
I'm not good at English,please forgive.

Many times!But this is the moment the particle accelerator is started.

MC version:1.10.2
Nuclear Physics version:  nuclearphysics-1.10.2-0.1.24
Forge version:12.18.3.2511

crash reports：
https://paste.ubuntu.com/26365549/

**Comment by halvors** [comment]
@ZHENGLOC Are you using a chunkloader block? The issue seems to be related to chickenbones's chunkloader.

**Comment by ZHENGLOC** [comment]
@halvors Yes, I installed chickenbones chunkloader,but I deleted that,it can work.

**Comment by halvors** [comment]
@ZHENGLOC Did it work without the chunkloader? Is the chunkloader next to the particle accelerator controller block. If you chunkload, make sure that is loaded.

**Comment by ZHENGLOC** [comment]
NO,I did not loaded,I did not place the chunkeloader in the overworld.

**Comment by halvors** [comment]
@ZHENGLOC Does the server crash instantly when launched? I cannot see that this bug is related to the Particle Accelerator...

**Comment by halvors** [comment]
@ZHENGLOC I need more information about this issue, can you somehow confirm that it's related to Nuclear Physics?

**Comment by ZHENGLOC** [comment]
@halvors Sometimes there is no problem with start，But after working for a while, it crashed.When loading the server, there is a chance that it will crash immediately, sometimes crashing in the chunk where the particle accelerator is loaded.If you don't build an accelerator, it won't crash.

**Comment by halvors** [comment]
@ZHENGLOC Hmm. Do you got more crash logs from cases when this happens?

**Comment by ZHENGLOC** [comment]
This is new logs and crash
https://paste.ubuntu.com/p/F64czFtdyk/
https://paste.ubuntu.com/p/ZNw29VpRrK/

**Comment by halvors** [comment]
@ZHENGLOC Those crash logs is not related to Nuclear Physics. You should reconsider using chicken bones's chunkloaders as there is where the crash happens.

**Comment by ZHENGLOC** [comment]
@halvors OK,I get it.I'm sorry did not help you.

**Comment by halvors** [comment]
No problem :-)
