### ISSUE TITLE
Unable to extract antimatter from Particle Accelerator

### ISSUE THREAD

**Issue by jdawg3636** [halvors/Quantum#18]
![2018-04-02_21 27 34](https://user-images.githubusercontent.com/20378095/38225990-efe1f880-36bc-11e8-82b4-7bc11da57489.png)

Particle accelerator doesn't seem to transfer its antimatter to cells - not sure if this is a bug or if I'm just doing it wrong.

MC Version: 1.12
Nuclear Physics Version: 0.1.27

**Comment by halvors** [comment]
@jdawg3636 I will have to look into this. Thanks for reporting! 
Could you just verify something for me, is the cells you've inserted brand new, or have the been used before? Used to store water, deuterium or tritium?

**Comment by jdawg3636** [comment]
They were pulled straight out of JEI - never been used before

(JEI Version 4.8.5.147, in case that matters)

**Comment by halvors** [comment]
Did some testing, confirmed to be an issue in 1.12.2. Currently working fine for 1.10.2. Will investigate further.

**Comment by halvors** [comment]
@jdawg3636 Bug fixed, closing this issue. Make sure to grab version 0.1.28 containin the fix :)
