### ISSUE TITLE
Hazmat Suit Has No Texture When Worn

### ISSUE THREAD

**Issue by jdawg3636** [halvors/Quantum#20]
![noarmor](https://user-images.githubusercontent.com/20378095/38771900-ea664360-3ff0-11e8-8fa9-72fbf50b1bf7.png)
![withhazmat](https://user-images.githubusercontent.com/20378095/38771901-ea790af4-3ff0-11e8-8464-e108b559eabc.png)

MC Version: 1.12.2
Nuclear Physics Version: 0.1.30

**Comment by halvors** [comment]
Fixed in 4aa7a574386e754f38f23c84bed141c23b150ea0, will be in next release. Thanks for reporting!
