### ISSUE TITLE
Fusion reactor stops working after a while

### ISSUE THREAD

**Issue by Njet75** [halvors/Quantum#23]
Get this text in log.
Latest build
[fusion.txt](https://github.com/halvors/Nuclear-Physics/files/1916229/fusion.txt)
Then the fusion stops boiling water and no Power and movment of turbines.
Restart the server helps.

Best Michael

**Comment by halvors** [comment]
@Njet75 What version are you on? And what Forge version?

**Comment by Njet75** [comment]
Tested with Forge 2655 and 2618 and nuclearphysics-1.12.2-0.1.31.jar and nuclearphysics-1.12.2-0.1.30.jar .
Diffrent constellations with these versions.
Same result.Takes diffrent amount of time until the log shows.
/Michael

**Comment by Njet75** [comment]
[crash-2018-04-18_20.11.44-server.txt](https://github.com/halvors/Nuclear-Physics/files/1925244/crash-2018-04-18_20.11.44-server.txt)
Also been getting this crasch.
From timt to time.

Best Michael

**Comment by halvors** [comment]
@Njet75 That last crash, do you do anything specific when that happens?

**Comment by Njet75** [comment]
Only moving around nearby.

**Comment by halvors** [comment]
@Njet75 I've tried to look into the first issue, and i might possibly have found a fix. But i'm having a hard time reproducing the issue, so could you please help me out by trying this dev build?
https://halvors.org/download/nuclearphysics-1.12.2-0.1.33-dev.jar

**Comment by Njet75** [comment]
Of Course :).
Testing and will get back with result.

/Michael

**Comment by Njet75** [comment]
[fusion II.txt](https://github.com/halvors/Nuclear-Physics/files/1933447/fusion.II.txt)
Witch Forge did you build aiganst?
Got more text in log with the dev version.
It might be a issue with other mod or Forge fluidhandler 
Gonna test some more
/Michael

**Comment by halvors** [comment]
@Njet75 Hmm, so you use GasFunnel's in your setup, not ElectricTurbines?

Could you try out the lastest  build, it contains some fixes that possibly solves the issue.

**Comment by halvors** [comment]
@Njet75 Think i figured what's wrong here. Will do some testing and get back to you with more details!

**Comment by halvors** [comment]
@Njet75 There still seems to be som funky buisness going on, but atleast now it doesn't hard crash like before. I'll continue looking into this, but in the meantime you could try out this: https://halvors.org/download/nuclearphysics-1.12.2-0.1.34-dev.jar

Let me know about your experience with it 😃

**Comment by Njet75** [comment]
With the new dev build the reactor dont stop working.
Instead it crashes but nothing points to Nuclear Physics.
Maybe you can make sense of it?
I´ll post the log next time it crasches.
Heres the crash log

[crash-2018-04-21_21.41.27-server.txt](https://github.com/halvors/Nuclear-Physics/files/1934978/crash-2018-04-21_21.41.27-server.txt)

And heres the log


[fusion III.txt](https://github.com/halvors/Nuclear-Physics/files/1934998/fusion.III.txt)

Hope this helps. :)

/ Michael

**Comment by halvors** [comment]
@Njet75 I also get the warnings in the log, this is because Nuclear Physics is still experiencing a small bug, but that is a bug that does not break gameplay, what's actually happening is that sometimes it fails adding temperature to a block, and instead it does so the next tick.
Solution so far is a but noisy, you may see some errors in the log, but it will not crash game.

The actual game crash you're experiencing is by other developers suggested to be because of Optifine. Could you check with you're enviroment if the game crash still happens with Optifine removed?

EDIT: I think the issue here is that you'r having Optifine installed on your server... Or am i wrong here?

**Comment by Njet75** [comment]
I agree .
I think nuclearphysics-1.12.2-0.1.34-dev.jar did the trick.
The reactor works perfect and something else is crashing my game.

**Comment by halvors** [comment]
Are you running a server or just client? So optifine is not installed on the server?

**Comment by Njet75** [comment]
I´m running on client for now.
My modpack is still buggy.
Downgraded to Forge 2618 and extrautils2-1.12-1.7.2.
Been running for Three hours with no crash.
Reactors work perfect.
Have two setups. One with gasfunnels and one without.

**Comment by halvors** [comment]
@Njet75 Excellent, any reason you're not running the latest RB of Forge? It's now 2655 for 1.12.2.

**Comment by Njet75** [comment]
I was running 2655 but I knew 2618 was stable.
Will try 2655 again and if it doesn´t crash I will be running it again.

**Comment by halvors** [comment]
@Njet75 Oh i see.

**Comment by halvors** [comment]
@Njet75 This is finally solved in latest release.
