### ISSUE TITLE
Mod localisation names issue

### ISSUE THREAD

**Issue by Attakajakka** [halvors/Quantum#24]
All of the items and any of the text shows us as item.nuclearphysics.darkmatter_cell for example and all of the items are doing this on nuclearphysics-1.12.2-0.1.31

**Comment by halvors** [comment]
Fixed in commit 3732df656f18ed33f916baf1c8ab2353f06e66dc.

**Comment by halvors** [comment]
This bug is fixed in latest release. Thanks @Attakajakka for reporting!
