### ISSUE TITLE
Thermometer can not send redstone signal?

### ISSUE THREAD

**Issue by ZHENGLOC** [halvors/Quantum#28]
This may be a bug or my way is wrong.
https://i.imgur.com/Cp4tQkH.png

**Comment by ZHENGLOC** [comment]
game version is 1.7.10

**Comment by halvors** [comment]
@ZHENGLOC Thanks you so much for reporting! The issue is fixed and will be in the next release.

**Comment by ZHENGLOC** [comment]
@halvors  Thank you! I think this mod is will be  better and better!

**Comment by halvors** [comment]
@ZHENGLOC This is fixed in latest release.
