### ISSUE TITLE
Update 1.35 Steam Texture Rendering issue

### ISSUE THREAD

**Issue by ZHENGLOC** [halvors/Quantum#32]
Before updating
https://i.imgur.com/s1g82mr.jpg
Updated
https://i.imgur.com/dehb9zB.png

**Comment by ZHENGLOC** [comment]
Game version is 1.7.10

**Comment by halvors** [comment]
@ZHENGLOC I cannot reproduce this to be just on 0.1.35, may it be that it was never working?
The steam may be from some other mod also, as lot of mods register steam as a fluid. I'll investigate when i have time :)
