### ISSUE TITLE
Game crash every time i enter a world

### ISSUE THREAD

**Issue by collwee** [halvors/Quantum#33]
crashlog  https://gist.github.com/collwee/7aa96d8900740b3d030baf75a5b22846
log  https://gist.github.com/collwee/3126f07f1cf95f9ae1743240c704fea8

it happened when i was travelling in a world and it crashed and every time i try to reenter the world it crash.

i don't know if that help but the crash happened when entering a magical forest biomes from thaumcraft.

**Comment by collwee** [comment]
after testing again it seams to happen in every new world that i create

**Comment by collwee** [comment]
this issue look related but for me it happen in 1.12.2 https://github.com/halvors/Nuclear-Physics/issues/22

**Comment by halvors** [comment]
@collwee Is it crashing when creating a new world without a particle accelerator as well?

**Comment by collwee** [comment]
yes

**Comment by collwee** [comment]
@halvors i have sent to you on discord a link of my modpack. it will crash every time you try to enter a world

**Comment by halvors** [comment]
@collwee I'm having a hard time reproducing this crash, does it crash in SinglePlayer or do you run a server?

**Comment by collwee** [comment]
singleplayer

**Comment by collwee** [comment]
@halvors the only thing that could change between the modpack that i send you would be the java version im using java 8 update 171 released on April 17. on what java update are you running ?

**Comment by halvors** [comment]
@collwee Same as you, i'll look into this when i have some spare time :)

**Comment by halvors** [comment]
@collwee Can you try running only Nuclear-Physics and an other mod on the same world? (Just remember to take a backup of it first as all blocks from other mods will dissapear).

I cannot reproduce you're issue with my test environment.

**Comment by halvors** [comment]
@collwee Have you experienced this with the latest release? I have a hard time reproducing this now...

**Comment by nictrace** [comment]
nuclearphysics.common.entity.EntityParticle saving to NBT crashes with NullPointer

**Comment by halvors** [comment]
@nictrace Have you managed to reproduce this? Couldn't make it crash in my test environment...

**Comment by nictrace** [comment]
I can't. Topic starter has many mods, some of them seems to have errors too

**Comment by halvors** [comment]
@nictrace Then we'll mark this as solved. @collwee Feel free to open a new issue if this still is a problem on latest version of the mod and Forge.
