### ISSUE TITLE
Crash when fusion reactor been running a while.

### ISSUE THREAD

**Issue by Njet75** [halvors/Quantum#34]
Experince crash with no direct link to Nuclear-Physics.
I´ll tested thru 194 mods and when I take out this mod it doesn´t crash.
Started happen whith nuclearphysics-1.12.2-0.1.34-dev and still present in nuclearphysics-1.12.2-0.1.35.
look in debug log 3 timestamp 14:21:17.
Hope this helps.
[crash-2018-04-29_13.55.54-server.txt](https://github.com/halvors/Nuclear-Physics/files/1960033/crash-2018-04-29_13.55.54-server.txt)
[debug-3.log](https://github.com/halvors/Nuclear-Physics/files/1960041/debug-3.log)

Might be a conflict with journeymap because I get this log sometime.
[2018-04-28-3.log](https://github.com/halvors/Nuclear-Physics/files/1960066/2018-04-28-3.log)

*Edit /I Think the crash happens when the server lags.
/Michael

**Comment by halvors** [comment]
@Njet75 Hmm. How often does this happen? Having a hard time tracking down this, this crash should not happen at all....

**Comment by halvors** [comment]
@Njet75 Could you also try this without OptiFine? Some other Forge modders thought maybe that is the issue.

**Comment by Njet75** [comment]
It happens randomly.
I will test without Optifine but pretty sure I did try without.
It might be another mod that does something strange.
I keep testing and get back.

Michael

**Comment by Njet75** [comment]
Must show you this.
Haha Something Went really wrong with my testing.:)
This reactor worked with nuclearphysics-1.12.2-0.1.33-dev but stpoed after 5 min.
Tested with latest build nuclearphysics-1.12.2-0.1.35 and this happens.
Shortly after the server crashed.
Tryed removing Optifine but will test Weather2 mod.
Just had to show it :)

![2018-05-03_20 54 18](https://user-images.githubusercontent.com/8996171/39597243-0f5ec560-4f15-11e8-94a5-1acb92972f35.png)

**Comment by halvors** [comment]
@Njet75 So you mean plasma is destroying the electromagnet blocks?

EDIT: I confirmed and fixed the plasma escaping reactor issue, will be some time to next release though.

**Comment by Njet75** [comment]
No worries.Only glad if I can be of help.:)
I´ll keep on testing meanwhile.

**Comment by Njet75** [comment]
Done some more testing.
With latest build nuclearphysics-1.12.2-0.1.36 no plasma spawn .
I reverted back to nuclearphysics-1.12.2-0.1.28 and found out that maybe the reactor stops because
of the Mekanism mod.
When I replaced the pipes the reactor started working again.
Will do some more testing and come back.

/Michael

**Comment by halvors** [comment]
@Njet75 Do you mean that no plasma spawns at all in the fusion reactor or that it doesn't run wild?

**Comment by nictrace** [comment]
I know this error, ConcurrentModificationException occurs when ArrayList element was removed inside a loop by these ArrayList's elements

**Comment by Njet75** [comment]
No plasma spawns at all in the fusion reactor.
No relevanse to Mekanism mod.
/Michael

**Comment by halvors** [comment]
@nictrace Yeah, it's supposed to be fixed now. Problem was multitreading where different threads was altering the HashMap storing values.

**Comment by halvors** [comment]
@Njet75 Do you still experience this issue? Is the crash still occuring with the latest version? Plasma issue should be fixed now.

**Comment by Njet75** [comment]
Yes I agree. The latest build fixes this issue.Been running server for 4 hours and still no stopping.
But I get lagspikes with latest build every minute.Is the thread saving something?
Maybe Close this issue and open new?
Thanks for the great work :)

/Michael
