### ISSUE TITLE
Gas Centrifuge cannot be connected by liquid pipe

### ISSUE THREAD

**Issue by ZHENGLOC** [halvors/Quantum#39]
https://i.imgur.com/fU7JyQ6.png

**Comment by ZHENGLOC** [comment]
Game version 1.7.10 
mod version 0.1.36

**Comment by halvors** [comment]
@ZHENGLOC You're right, thanks for reporting, this is a think that missed my attention when porting, it's an easy quick fix. It simply needs to be implemented 👍

**Comment by halvors** [comment]
Fix released, grab the 0.1.37 version 👍
