### ISSUE TITLE
How to start Plazma Heater

### ISSUE THREAD

**Issue by TechinicFiles** [halvors/Quantum#45]
I have given the Plazma heater as much Deuterium and Tritium it'll consume and given it energy but it will not produce plazma. Where am i going wrong??
![image](https://user-images.githubusercontent.com/28156689/41190875-596c7450-6bde-11e8-9631-c12c15b2a4ae.png)

![image](https://user-images.githubusercontent.com/28156689/41190883-71e184e4-6bde-11e8-81f8-bec44d89f2b6.png)

![image](https://user-images.githubusercontent.com/28156689/41190886-819a5262-6bde-11e8-8973-ad43fd8d4de6.png)

**Comment by TechinicFiles** [comment]
Update: It seems the plazma heater is filling with plazma (About 2000L now) but i see no plazma in the rings and the thermometer is sticking at a solid 200 kelvin.

**Comment by halvors** [comment]
@TechinicFiles Plasma heater does not need to be placed inside reactor. (Or be a part of the constrution)

Plasma can be piped from the plasma heater to the reactor cell. What you're doing wrong here is that plasma heater is placed where reactor cell is supposed to be.

Try placing the reactor cell there instead, and pipe plasma to it from the plasma heater.

**Comment by TechinicFiles** [comment]
Thanks for the reply. I feel silly now. Could you advise how to extract plasma from it? Just so i know when i go back in game, Im guessing anyway that the only thing that can be extracted from the heater is plasma

**Comment by TechinicFiles** [comment]
Okay now i've filled the reactor cell with plasma in the centre of the ring. It is depleting plasma yet no heat is produced nore is there any signs of life
![image](https://user-images.githubusercontent.com/28156689/41207344-4acbc91c-6d0c-11e8-8422-7e5412af1467.png)

![image](https://user-images.githubusercontent.com/28156689/41207357-6304dd0c-6d0c-11e8-836d-039dcca48702.png)

**Comment by halvors** [comment]
What mc version are you on?

**Comment by TechinicFiles** [comment]
This version is 1.7.10
File version is the curse forge version: nuclearphysics-1.7.10-0.1.37 which i think is the current lastest

**Comment by TechinicFiles** [comment]
@halvors I think i may have a solution to narrow down to. It could possibly be an issue with Electromagnets. Because now that i've decided to move onto particle accelerators i can't seem  to get it to work either. Everything is how it should be. A 30x30 ring of mostly electromagnets and a line of EM glass. But it keeps giving me the failed to emit error, even after attempting to rotate the machine, so i suspect the EMs

**Comment by halvors** [comment]
There is other issues causing this to not always work. Closing this for now.
