### ISSUE TITLE
Particle Accelerator stuck in idle state

### ISSUE THREAD

**Issue by kyagloski** [halvors/Quantum#48]
Im trying to start the particle accelerator and the status is stuck in idle, I've changed the way the block itself is facing in every orientation but it still says its idle. In some orientations the particle stays in place and make the noise but does not move. In other orientations the partilce will move forward a few blocks and explode creating antimatter.

I tested it with just Nuclear Physics and Mekanism installed and it still occured so I don't think its a mod conflict problem.

**Comment by halvors** [comment]
@Chaos249 This should now be solved, please do report if this solves this issue for you :) New release coming up soon!
