### ISSUE TITLE
Machines screw up inventory lighting

### ISSUE THREAD

**Issue by kmecpp** [halvors/Quantum#49]
In 1.7.10, most of the machines, including the chemical extractor, centrifuge, plasma heater, and quantum assembler, screw up the inventory lighting when their items are rendered. Here is an example:

**Before**
![image](https://user-images.githubusercontent.com/6520738/43787174-6b19753a-9a38-11e8-9a98-ea5cb046be46.png)

**After**
![image](https://user-images.githubusercontent.com/6520738/43787199-758f7adc-9a38-11e8-9e53-d2e47acc2789.png)

**Comment by halvors** [comment]
@kmecpp Thanks for reporting, unclear how this happens but i suspect it's a caused by our custom renderer on order to get itemrendering working in 1.7.10 as in newer versions.

**Comment by halvors** [comment]
@kmecpp Have you confirmed that this fixes the issue?

**Comment by kmecpp** [comment]
Yes. It did for me.

**Comment by halvors** [comment]
@kmecpp Thanks for help, considering this fixed then.
