### ISSUE TITLE
Memory Leak with Plasma Heaters

### ISSUE THREAD

**Issue by kmecpp** [halvors/Quantum#50]
On 1.7.10 there's a memory leak with Plasma heaters. I'm not sure how to replicate the bug but I was just fooling around with Reactor cells trying to make a fission reactor and the game lagged out later

![image](https://user-images.githubusercontent.com/6520738/43994417-6cd2ff24-9d6a-11e8-8eb6-83dd4f616a9c.png)

**Comment by halvors** [comment]
@kmecpp Thanks.

@nictrace Maybe you could have a look at this?

**Comment by nictrace** [comment]
ok, I'll see

**Comment by halvors** [comment]
This should be fixed by @kmecpp in his PR.
