### ISSUE TITLE
Fission reactors not working?

### ISSUE THREAD

**Issue by kmecpp** [halvors/Quantum#51]
Fission reactors don't appear to be working correctly in 1.7.10. I also tried the same setup with gas funnels as well as gas funnels with pipes, and when connected to a mekanism energy cube. The turbines don't spin

![image](https://user-images.githubusercontent.com/6520738/43994530-9341a23a-9d6c-11e8-94fb-b7c3f9409d0f.png)

**Comment by halvors** [comment]
The actual problem here is that water is never boiled, and thereby steam not generated which doesn't make the turbines spin. Closing this issue and tracking this in #47. @kmecpp Thanks for reporting! :)
