### ISSUE TITLE
Particle accelerator creates antimatter instantly

### ISSUE THREAD

**Issue by Soup-64** [halvors/Quantum#58]
- particle goes from 0 to max velocity instantly or spawns in and de-spawns shortly after
-found in 1.12.2, found in nuclearphysics version 0.1.37

**Comment by halvors** [comment]
@Bm-64 Can you reproduce this in 0.1.38?

**Comment by Soup-64** [comment]
.1.38 had an instant crash issue in 1.12; trying it now in the latest

**Comment by Soup-64** [comment]
The insta bug seems fine now, and the de-spawn issue turned out to be a rf thru-put problem.
