### ISSUE TITLE
Config Issues

### ISSUE THREAD

**Issue by NGSquirrely** [halvors/Quantum#70]
All configuration should be done in type **"double"** instead of type **"int"**, allowing outputs to be halved. 

furthermore, some looking into might be needed for joule conversion. In my test environment, I adjusted joule conversion rates so that the nuclear physics constructs would use much more than normal. While the interface adjusted the new value for the particle accelerator, saying "Using 10GJ of power" - the **mekanism** elite cube would stay constantly full at 120MJ. There are 1000MJ in 1GJ, so it should have been completely drained. To complete this test, I removed the batterybox from the particle accelerator, and it used KJ still.

**Comment by NGSquirrely** [comment]
- [ ] 

- [ ] 

- [ ]

**Comment by halvors** [comment]
@NGSquirrely I agree with the joule conversion. But the other option that is currently integers is that for a a reason. That reason being Forge requires whole numbers of fluid stacks.
